version: "3.8"
services:
  app:
    build:
      context: .
    image: hunnidbands100/home-library-service:nodejs2023-uz-service-app
    ports:
      - "${PORT}:${PORT}"
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
      - logs:/app/logs
    networks:
      - home-library-network

  postgres:
    build: ./db/
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - pglogs:/logs
    networks:
      - home-library-network

volumes:
  pgdata:
  pglogs:
  logs:
networks:
  home-library-network:
    driver: bridge
